---
useful_tools_headless:
  - aria2
  - binwalk
  - curl
  - default-jdk-headless
  - dos2unix
  - htop
  - jq
  - masscan
  - nload
  - nmap
  - p7zip-full
  - parallel
  - python3-venv
  - resolvconf
  - ripgrep
  - screen
  - slowhttptest
  - sysstat
  - vim
  - wireguard
  - xsel


useful_tools_gui:
  - default-jdk
  - libnss3-tools
  - simplescreenrecorder


packages_to_uninstall:
  - atril
  - gimp
  - gnome-mines
  - gnome-sudoku
  - hexchat
  - parole
  - pavucontrol
  - rhythmbox
  - rhythmbox-data
  - rhythmbox-plugin-alternative-toolbar
  - rhythmbox-plugins
  - sgt-launcher
  - sgt-puzzles
  - simple-scan
  - synaptic 
  - thunderbird
  - thunderbird-locale-en
  - thunderbird-locale-en-us
  - transmission-common
  - transmission-gtk
  - tumbler
  - update-notifier
  - xfburn
  - xfce4-dict
  - xterm




