- name: Copy any useful files to home directory
  copy:
    src: homedir/  # from role's files/ directory
    dest: "/home/{{ username }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0400

